[build]
  publish = "dist"
  command = "yarn build"

[context.production]
  [context.production.environment]
    NODE_VERSION = "12"
    REACT_APP_COVID_URL = "https://api.covid19api.com"
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
