name: ci
on: [push]

jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('yarn.lock') }}

  format:
    runs-on: ubuntu-18.04
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('yarn.lock') }}
      - run: yarn format

  lint:
    runs-on: ubuntu-18.04
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('yarn.lock') }}
      - run: yarn lint

  deploy:
    runs-on: ubuntu-18.04
    needs: [format, lint]
    if: github.ref == 'refs/heads/master'
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('yarn.lock') }}
      - run: yarn build
